spring:
  data:
    mongodb:
      uri: "mongodb://192.168.0.16:27017/itsdb"
  resources:
    static-locations: "file:./uploads,classpath:/static/"

its:
  admin-initializer:
    email: "admin@mail.com"
    username: "admin"
    password: "password"
  security:
    password-recovery-url: "http://localhost:4200/password-reset?token="

  file-store:
    basePath: "uploads"


